Install `cargo-outdated` with `cargo-binstall`
This should get us a version that is built with/against more recent versions of Cargo, which will in turn fix the error we're seeing in CI:

```
error: failed to parse manifest at `/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/base64ct-1.8.0/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.83.0).
  Consider trying a more recent nightly release.
```

We could also use `cargo install` but it is *very* slow (4m).

This change also updates all uses of `checkout@v2` to `checkout@v4`. Unfortunately, this is **not** just an unrelated cleanup: `checkout@v4` [stores an access token in the local Git repo config](https://github.com/actions/checkout/blob/09d2acae674a48949e3602304ab46fd20ae0c42f/README.md#checkout-v4), which in turn [gets picked up by `cargo-binstall`](https://github.com/cargo-bins/cargo-binstall/blob/8aac5aa2bf0dfaa2863eccad9f43c68fe40e5ec8/crates/bin/src/args.rs#L384-L386) so it can access the Github REST API. Without the update, `cargo binstall` fails and falls back to compiling from source.